export const routes = [
  { path: '/', name: 'Business HQ' },
  { path: '/passport', name: 'BizCredit Passport' },
  { path: '/profile', name: 'Profile' },
  { path: '/credit-architect', name: 'Credit Architect' },
  { path: '/directory', name: 'Directory' },
  { path: '/tradeline-planner', name: 'Tradeline Planner' },
  { path: '/roadmap', name: 'Roadmap' },
  { path: '/alerts', name: 'Alerts' },
  { path: '/score-tracker', name: 'Score Tracker' },
  { path: '/funding-readiness', name: 'Funding Readiness' },
  { path: '/document-index', name: 'Document Index' },
  { path: '/denial-recovery', name: 'Denial Recovery' },
  { path: '/imports', name: 'Imports' },
  { path: '/exports', name: 'Exports' },
  { path: '/schemas', name: 'Schemas' },
  { path: '/funding-tools', name: 'Funding Tools' },
  { path: '/gpt-directory', name: 'GPT Directory' },
  { path: '/notion-sync', name: 'Notion Bridge' },
  { path: '/settings', name: 'Settings' }
];
